version: "2.2"

services:
  app:
    build: .
    env_file:
      - .dev.env
    ports:
      - "4000:4000"
    networks:
      - dev-users-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    hostname: mongodb
    #volumes:
    #  - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    networks:
      - dev-users-network

networks:
  dev-users-network:
    name: dev-users-network
    driver: bridge