version: "2.2"

services:  
  users_app:
    build: .
    env_file:
      - .dev.env
    ports:
      - "4000:4000"
    depends_on:
      - users_mongo
  users_mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - ./test-docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro