version: "2.2"

services:
  app:
    build: .
    environment:
      - PORT = "4000"
      - DB_CNN = "mongodb://db:27017/test"
      - SECRET_JWT_SEED = ""
    ports:
      - "4000:4000"
    networks:
      - dev-users-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      - dev-users-network
  
networks:
  dev-users-network:
    name: dev-users-network
    driver: bridge