name: Build and deploy a container to an Azure Web App for testing PR

env:
  AZURE_WEBAPP_NAME: pr-users-uniquegroup-match-fiuba
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_PR_USERS_PUBLISH_PROFILE }}
  
on:
  pull_request:
    types: [opened, synchronize, reopened, close]
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Build container image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: false
          tags: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
          file: ./Dockerfile

      - name: List files in current working directory
        run: ls -R
          
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
