name: Build and deploy a container to an Azure Web App

on:
  push:
    branches: [ "main"]
  pull_request:
    types: [opened, synchronize, reopened, close]
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Environment File
        run: |
          echo "PORT=${{ vars.PORT }}" > .env    
          echo "HOST=${{ vars.HOST }}" >> .env
          echo "DB_CNN=${{ secrets.DB_CNN }}" >> .env
          echo "SECRET_JWT_SEED=${{ secrets.SECRET_JWT_SEED }}" >> .env
          
          echo "EMAIL_CHECK_APP=${{ vars.EMAIL_CHECK_APP }}" >> .env
          echo "SERVICE_EMAIL_APP=${{ vars.SERVICE_EMAIL_APP }}" >> .env
          echo "HOST_EMAIL_APP=${{ vars.HOST_EMAIL_APP }}" >> .env
          echo "PORT_EMAIL_APP=${{ vars.PORT_EMAIL_APP }}" >> .env
          echo "USER_APP_EMAIL=${{ vars.USER_APP_EMAIL }}" >> .env
          echo "PASS_EMAIL_APP='${{ secrets.PASS_EMAIL_APP }}'" >> .env
          
          echo "LOG_FILENAME=${{ vars.LOG_FILENAME }}" >> .env
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: hgmart
          password: ${{ secrets.HGMART_PAT }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: List directory contents
        run: ls -al

      - name: Display Environment File
        run: cat .env

      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
