name: Tests coverage CI

on:
  push:
    branches: [ "main", "coveral-integration" ]
  pull_request:
    branches: [ "main", "coveral-integration" ]

jobs:
  coverall:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create Environment File
      run: |
        echo "PORT=${{ vars.PORT }}" > .env    
        echo "HOST=${{ vars.HOST }}" >> .env
        echo "DB_CNN=${{ secrets.DB_CNN }}" >> .env
        echo "SECRET_JWT_SEED=${{ secrets.SECRET_JWT_SEED }}" >> .env

    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev @babel/core @babel/preset-env babel-jest

    - name: Run tests
      run: npm test

    - name: Run coverage and report to Coveralls
      run: npm run coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }} 