name: Tests coverage CI

on:
  push:
    branches: [ "main", "coveral-integration" ]
  pull_request:
    branches: [ "main", "coveral-integration" ]

jobs:
  coverall:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Environment File
      run: |
        echo "PORT=${{ vars.PORT }}" > .env    
        echo "HOST=${{ vars.HOST }}" >> .env
        echo "DB_CNN=${{ secrets.DB_CNN }}" >> .env
        echo "SECRET_JWT_SEED=${{ secrets.SECRET_JWT_SEED }}" >> .env

    - name: Install dependencies
      run: |
        npm install --force

    - name: Run coverage and report to Coveralls
      if: always()
      run: npm run coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }} 