components:
    schemas:
        TokenPayload:
            type: object
            properties:
                uid:
                    type: string
                    description: unique user id 
                role:
                    type: string
                    description: cliente or administrador
                    enum: [administrador, cliente]
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.
        UserSharedData:
            type: object
            properties:
                uid:
                    type: string
                    description: unique user id 
                email:
                    type: string
                    description: unique user email              
                role:
                    type: string
                    description: cliente or administrador
                    enum: [administrador, cliente]
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.
                verified:
                    type: boolean
                    description: unique. Indicates whether the user has verified their account.
            required: 
                - email
                - password
                - role
                - blocked
                - verified
            example:
                id: 645547541243dfdsfe2132142134234203
                email: rafaelputaro@gmail.com
                role: administrador
                blocked: false
                verified: true
        UserCreateData:
            type: object
            properties:
                uid:
                    type: string
                    description: unique user id 
                email:
                    type: string
                    description: unique user email              
                role:
                    type: string
                    description: cliente or administrador
                    enum: [administrador, cliente]
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.
            required: 
                - email
                - password
                - role
                - blocked
            example:
                email: carlos@mail.com
                password: cli123te1*
                role: cliente
                blocked: false
        UserUpdateData:
            type: object
            properties:
                email:
                    type: string
                    description: unique user email              
                password:
                    type: string
                    description: user password. Numbers, letters and at least one symbol
                    minLength: 6
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.
            example:
                email: carlos@mail.com
                password: cli123te1*
                blocked: false